language: java
jdk:
  - oraclejdk7
  - openjdk7

install:
  - mvn install dependency:resolve -Dmaven.test.skip -Dmaven.javadoc.skip

script: 
  - mvn verify -Pcassandra-2.0 -Dmaven.javadoc.skip --quiet

after_success:
  - mvn clean cobertura:cobertura coveralls:rep

notifications:
  irc: "irc.freenode.net#blueflood"
  email:
    recepients:
      - blueflood-discuss@googlegroups.com
